-- CreateTable
CREATE TABLE "aos" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "budget" TEXT NOT NULL DEFAULT '',
    "lot" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'open',
    "requestedTrade" TEXT NOT NULL DEFAULT '',
    "visibilityScope" TEXT NOT NULL DEFAULT 'public',
    "ownerUserId" TEXT NOT NULL,
    "ownerProfileType" TEXT NOT NULL DEFAULT 'client',
    "projectId" TEXT,
    "createdByClient" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "aos_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "aos" ADD CONSTRAINT "aos_ownerUserId_fkey" FOREIGN KEY ("ownerUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
