services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: meereo-web
    restart: unless-stopped
    ports:
      - '8080:80'

networks:
  default:
    driver: bridge
