const { Router } = require('express')
const { getPrisma } = require('../db')
const { requireAuth } = require('../middleware/auth')
const { createError } = require('../middleware/errorHandler')

const router = Router()

// GET /api/aos — tous les AOs publics (pro/client peuvent voir)
// Filtre côté backend selon visibilityScope + ownerUserId pour le client
router.get('/', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const user = req.user

    let where = {}

    if (user.type === 'client') {
      // Le client voit TOUS ses AOs (open, attributed, closed…)
      where.ownerUserId = user.id
    } else if (user.type === 'pro') {
      // Pro : uniquement les AOs ouverts
      where.status = 'open'
      // Le pro voit les AOs publics + ceux trade_only si son métier correspond
      // On retourne tout open et on laisse le front filtrer par trade
      where.status = 'open'
    }
    // fournisseur ne voit pas les AOs par défaut

    const aos = await prisma.aO.findMany({
      where,
      orderBy: { createdAt: 'desc' },
    })
    res.json(aos)
  } catch (e) {
    next(e)
  }
})

// POST /api/aos — créer un AO
router.post('/', requireAuth, async (req, res, next) => {
  try {
    const {
      title, description, budget, lot, requestedTrade,
      visibilityScope, projectId, createdByClient, autoGenerated,
      ownerProfileType,
    } = req.body

    if (!title || !title.trim()) throw createError("Le titre de l'AO est requis", 400)

    const prisma = getPrisma()
    const ao = await prisma.aO.create({
      data: {
        title: title.trim(),
        description: description || '',
        budget: budget || '',
        lot: lot || '',
        status: 'open',
        requestedTrade: requestedTrade || lot || '',
        visibilityScope: visibilityScope || 'public',
        ownerUserId: req.user.id,
        ownerProfileType: ownerProfileType || req.user.type,
        projectId: projectId || null,
        createdByClient: createdByClient || req.user.type === 'client',
        autoGenerated: autoGenerated || false,
      },
    })
    res.status(201).json(ao)
  } catch (e) {
    next(e)
  }
})

// PATCH /api/aos/:id — modifier le statut ou les infos d'un AO
router.patch('/:id', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const existing = await prisma.aO.findUnique({ where: { id: req.params.id } })
    if (!existing) throw createError('AO introuvable', 404)
    if (existing.ownerUserId !== req.user.id) throw createError('Non autorisé', 403)

    const ao = await prisma.aO.update({
      where: { id: req.params.id },
      data: {
        title: req.body.title ?? existing.title,
        description: req.body.description ?? existing.description,
        budget: req.body.budget ?? existing.budget,
        lot: req.body.lot ?? existing.lot,
        status: req.body.status ?? existing.status,
        requestedTrade: req.body.requestedTrade ?? existing.requestedTrade,
        visibilityScope: req.body.visibilityScope ?? existing.visibilityScope,
      },
    })
    res.json(ao)
  } catch (e) {
    next(e)
  }
})

// DELETE /api/aos/:id — fermer/supprimer un AO
router.delete('/:id', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const existing = await prisma.aO.findUnique({ where: { id: req.params.id } })
    if (!existing) throw createError('AO introuvable', 404)
    if (existing.ownerUserId !== req.user.id) throw createError('Non autorisé', 403)
    await prisma.aO.update({ where: { id: req.params.id }, data: { status: 'cancelled' } })
    res.json({ success: true })
  } catch (e) {
    next(e)
  }
})

module.exports = router
