const { Router } = require('express')
const { getPrisma } = require('../db')
const { requireAuth } = require('../middleware/auth')
const { createError } = require('../middleware/errorHandler')

const router = Router()

// GET /api/aos — tous les AOs publics (pro/client peuvent voir)
// Filtre côté backend selon visibilityScope + ownerUserId pour le client
router.get('/', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const user = req.user

    let where = {}

    if (user.type === 'client') {
      // Le client voit ses AOs actifs (sauf cancelled/supprimés)
      where.ownerUserId = user.id
      where.status = { not: 'cancelled' }
    } else if (user.type === 'pro') {
      // Pro : uniquement les AOs ouverts
      where.status = 'open'
      // Le pro voit les AOs publics + ceux trade_only si son métier correspond
      // On retourne tout open et on laisse le front filtrer par trade
      where.status = 'open'
    }
    // fournisseur ne voit pas les AOs par défaut

    const aos = await prisma.aO.findMany({
      where,
      orderBy: { createdAt: 'desc' },
    })
    res.json(aos)
  } catch (e) {
    next(e)
  }
})

// POST /api/aos — créer un AO
router.post('/', requireAuth, async (req, res, next) => {
  try {
    const {
      title, description, budget, lot, requestedTrade,
      visibilityScope, projectId, createdByClient, autoGenerated,
      ownerProfileType,
    } = req.body

    if (!title || !title.trim()) throw createError("Le titre de l'AO est requis", 400)

    // Règle métier : le client ne peut créer un AO que pour un Bureau d'Architecture
    const isClient = req.user.type === 'client'
    const resolvedTrade = isClient ? "Bureau d'Architecture" : (requestedTrade || lot || '')

    const prisma = getPrisma()
    const ao = await prisma.aO.create({
      data: {
        title: title.trim(),
        description: description || '',
        budget: budget || '',
        lot: lot || '',
        status: 'open',
        requestedTrade: resolvedTrade,
        visibilityScope: visibilityScope || 'public',
        ownerUserId: req.user.id,
        ownerProfileType: ownerProfileType || req.user.type,
        projectId: projectId || null,
        createdByClient: createdByClient || req.user.type === 'client',
        autoGenerated: autoGenerated || false,
      },
    })

    // Broadcast new AO to all pros via socket (for real-time Bourse update)
    if (ao.visibilityScope === 'public' || ao.visibilityScope === 'trade_only') {
      try {
        const { getIo } = require('../socket')
        const io = getIo()
        if (io) {
          // Notify all connected pros about the new AO
          io.emit('ao:new', { id: ao.id, title: ao.title, trade: ao.requestedTrade })
        }
      } catch (_) {}
    }

    res.status(201).json(ao)
  } catch (e) {
    next(e)
  }
})

// PATCH /api/aos/:id — modifier le statut ou les infos d'un AO
router.patch('/:id', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const existing = await prisma.aO.findUnique({ where: { id: req.params.id } })
    if (!existing) throw createError('AO introuvable', 404)
    if (existing.ownerUserId !== req.user.id) throw createError('Non autorisé', 403)

    const ao = await prisma.aO.update({
      where: { id: req.params.id },
      data: {
        title: req.body.title ?? existing.title,
        description: req.body.description ?? existing.description,
        budget: req.body.budget ?? existing.budget,
        lot: req.body.lot ?? existing.lot,
        status: req.body.status ?? existing.status,
        requestedTrade: req.body.requestedTrade ?? existing.requestedTrade,
        visibilityScope: req.body.visibilityScope ?? existing.visibilityScope,
      },
    })
    res.json(ao)
  } catch (e) {
    next(e)
  }
})

// GET /api/aos/:id/dossier — récupérer le dossier auto-constitué depuis le référentiel entreprise
// Utilisé par un pro qui veut répondre à un AO — prépare automatiquement son dossier
router.get('/:id/dossier', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const ao = await prisma.aO.findUnique({ where: { id: req.params.id } })
    if (!ao) throw createError('AO introuvable', 404)

    // Récupérer les documents entreprise du professionnel
    const entrepriseDocs = await prisma.document.findMany({
      where: { userId: req.user.id, isEntreprise: true, parentId: null },
      orderBy: { createdAt: 'desc' },
    })

    // Récupérer le profil professionnel
    const user = await prisma.user.findUnique({
      where: { id: req.user.id },
      select: { id: true, name: true, company: true, publicId: true, onboardingData: true },
    })

    // Grouper les documents par catégorie
    const dossier = {
      entreprise: user,
      documents: {
        administratifs: entrepriseDocs.filter(d => ['rccm', 'attestation_fiscale', 'assurance', 'admin'].includes(d.category || d.type)),
        certifications: entrepriseDocs.filter(d => d.category === 'certification'),
        presentations: entrepriseDocs.filter(d => ['presentation', 'portfolio'].includes(d.category)),
        autres: entrepriseDocs.filter(d => !['rccm', 'attestation_fiscale', 'assurance', 'admin', 'certification', 'presentation', 'portfolio'].includes(d.category || d.type)),
      },
      totalDocuments: entrepriseDocs.length,
    }
    res.json(dossier)
  } catch (e) { next(e) }
})

// DELETE /api/aos/:id — supprimer un AO (hard delete si sans offres, sinon annulation)
router.delete('/:id', requireAuth, async (req, res, next) => {
  try {
    const prisma = getPrisma()
    const existing = await prisma.aO.findUnique({ where: { id: req.params.id } })
    if (!existing) throw createError('AO introuvable', 404)
    if (existing.ownerUserId !== req.user.id) throw createError('Non autorisé', 403)

    // Vérifier s'il existe des offres liées à cet AO
    const offersCount = await prisma.offer.count({ where: { aoId: req.params.id } })

    if (offersCount === 0) {
      // Aucune offre — suppression définitive
      await prisma.aO.delete({ where: { id: req.params.id } })
    } else {
      // Des offres existent — annulation douce
      await prisma.aO.update({ where: { id: req.params.id }, data: { status: 'cancelled' } })
    }

    res.json({ success: true })
  } catch (e) {
    next(e)
  }
})

module.exports = router
